resources:
  - crds.yaml
  - istio.yaml
  - net-istio.yaml
  - prometheus-operator.yaml

patches:
  - path: patches/istio-ingressgateway-nodeport.yaml
    target:
      kind: Service
      name: istio-ingressgateway
      namespace: istio-system
  - path: patches/knative-ingress-gateway-tls.yaml
    target:
      group: networking.istio.io
      version: v1beta1
      kind: Gateway
      name: knative-ingress-gateway
      namespace: knative-serving
